# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'compile'

- task: Bash@3
  displayName: ShiftLeft cli scan
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/ShiftLeftSecurity/sast-scan/releases/download/v1.0.8-test/scan -O $(Build.ArtifactStagingDirectory)/scan
      chmod +x $(Build.ArtifactStagingDirectory)/scan
      $(Build.ArtifactStagingDirectory)/scan -t java,depscan -o $(Build.ArtifactStagingDirectory)/CodeAnalysisLogs
      # sh <(curl https://slscan.sh/install)
      # $HOME/.local/bin/scan -t java,depscan -o $(Build.ArtifactStagingDirectory)/CodeAnalysisLogs
  env:
    WORKSPACE: https://github.com/prabhu/struts2-rce/blob/$(Build.SourceVersion)
    SCAN_DEBUG_MODE: debug

- task: PublishBuildArtifacts@1
  displayName: "Publish analysis logs"
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs"
    ArtifactName: "CodeAnalysisLogs"
    publishLocation: "Container"

